### ISSUE TITLE
Help with this driver?

### ISSUE THREAD

**Issue by andy83-projects** [RMoRobert/Hubitat#11]
I can detect the device, it gets detected by Habitat as a generic device.

Switch to this driver and I can't control the switch or see endpoints.

Might be the switch, but same brand and model as the driver.

Curious if you have suggestions?

**Comment by RMoRobert** [comment]
Please post any problems in the Hubitat Community forum. Most apps and drivers have a topic (thread) for discussion; if not, create one of your own. Be sure to specify the specific driver, as I cannot tell from the comment above, and this repository hosts several. Thanks!
