### ISSUE TITLE
Missing Import Statement - Advanced Inovelli Red Series Switch (LZW30-SN)

### ISSUE THREAD

**Issue by sdholden28** [RMoRobert/Hubitat#8]
For Advanced Inovelli Red Series Switch (LZW30-SN), line 32 should be "import java.util.concurrent.ConcurrentHashMap" and it is missing. Hubitat will not compile the driver without it, as line 85 and line 86 call the ConcurrentHashMap function which is undefined without the import. Adding the line mentioned above results in a successful compile and a properly functioning driver.

**Thanks so much for these drivers as the inovelli button assignments make operation in smart bulb mode really difficult.

**Comment by RMoRobert** [comment]
This should be fixed in 2.3.1, and I also addressed another issue I saw (Long vs. String where I expected a Long) that I hope doesn't break anything...
